### ISSUE TITLE
similar to Buffer.concat?

### ISSUE THREAD

**Issue by max-mapper** [kilianc/node-bufferjoiner#1]
in node you can do `Buffer.concat([new Buffer('hello '), new Buffer('world')]).toString()` to get `hello world`

does this module add additional functionality?

**Comment by max-mapper** [comment]
Oh i guess this is new in 0.8

**Comment by kilianc** [comment]
The main difference is that you can add chunks and it stores the total length.

``` js
req.on('data', function (chucnk) {
  bf.add(chunk)
}).once('end', function () {
  var payload = bf.join()
})
```

I can use  `Buffer.concat` inside de module itself, but it will cost compatibility with < 0.8.x

**Comment by max-mapper** [comment]
is that any more performant than this or is it just a lines of code difference?

```
var bf = []
req.on('data', bf.push)
.once('end', function () {
  var payload = Buffer.concat(bf)
})
```

**Comment by kilianc** [comment]
yes Buffer.concat iterates to get the total length ([doc](http://nodejs.org/api/buffer.html#buffer_class_method_buffer_concat_list_totallength))

So it becomes

``` js
var bf = []
vat totalBytes = 0
req.on('data', function (chunk) {
  totalBytes += chunk.length
  bf.push(chunk)
}).once('end', function () {
  var payload = Buffer.concat(bf, totalBytes)
})
```

that is exactly what my module does :)

**Comment by max-mapper** [comment]
OH I get it now, thanks for the doc link. You could do feature detection to use Buffer.concat internally and still support older nodes

**Comment by kilianc** [comment]
You're right, added to my todo :)
